---
- hosts: 172.31.90.140
  become: yes
  tasks:
    - name: Install the latest version of Apache
      yum: 
        name: httpd
        state: present
    - name: copy code to remote machine
      copy:
        src: index.htm
        dest: /var/www/html
    - name: start apache
      service:
          name: httpd
          enable: yes
          state: started
